# Generated by Django 5.0.2 on 2024-03-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViperApp', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
